# Generated by Django 2.1.5 on 2019-02-27 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='resourseurl',
        ),
        migrations.AddField(
            model_name='resource',
            name='resourceurl',
            field=models.URLField(blank=True, null=True),
        ),
    ]
